name: Deploy to GCP Private VM

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: elevated-valve-459107-h8
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-docker.pkg.dev/elevated-valve-459107-h8/backend/cafeboo:latest .

      - name: Push Docker Image
        run: |
          docker push asia-docker.pkg.dev/elevated-valve-459107-h8/backend/cafeboo:latest

      - name: SSH into GCP VM via IAP and Deploy
        run: |
          gcloud compute ssh dev-private-vm \
            --project=elevated-valve-459107-h8 \
            --zone=asia-northeast3-a \
            --tunnel-through-iap \
            --command="docker stop cafeboo || true && \
                      docker rm cafeboo || true && \
                      docker pull asia-docker.pkg.dev/elevated-valve-459107-h8/backend/cafeboo:latest && \
                      docker run -d --name cafeboo -p 8080:8080 \
                        -e SPRING_PROFILES_ACTIVE=prod \
                        -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                        -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_PASSWORD }} \
                        asia-docker.pkg.dev/elevated-valve-459107-h8/backend/cafeboo:latest"
