name: Deploy to GCP Private VM (Dev)

on:
  push:
    branches: [ release/2.0 ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_2 }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: master-isotope-462503-m9
          version: latest

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-northeast3-docker.pkg.dev/master-isotope-462503-m9/backend/cafeboo-back:latest .

      - name: Push Docker Image
        run: |
          docker push asia-northeast3-docker.pkg.dev/master-isotope-462503-m9/backend/cafeboo-back:latest 


      - name: SSH into GCP VM via IAP and Deploy
        run: |
            gcloud compute ssh dev-vm \
            --project=master-isotope-462503-m9 \
            --zone=asia-northeast3-a \
            --tunnel-through-iap \
            --command="
            
            # Redis 컨테이너 중지 및 제거 (기존 있으면)
              sudo docker stop redis || true && \
              sudo docker rm redis || true && \

            # Redis 컨테이너 실행
              sudo docker run -d --name redis \
                --restart=always \
                --network host \
                redis:7 && \

            # 기존 백엔드 컨테이너 정리
              sudo docker stop cafeboo-back || true && \
              sudo docker rm cafeboo-back || true && \
           
              sudo docker pull asia-northeast3-docker.pkg.dev/master-isotope-462503-m9/backend/cafeboo-back:latest && \
            
            # 백엔드 컨테이너 실행
              sudo docker run -d --name cafeboo-back --network host \
                --restart=always \
                -e DEV_DB_URL='${{ secrets.DEV_DB_URL }}' \
                -e DEV_DB_USERNAME='${{ secrets.DEV_DB_USERNAME }}' \
                -e DEV_DB_PASSWORD='${{ secrets.DEV_DB_PASSWORD }}' \
                -e SPRING_PROFILES_ACTIVE=dev \
                -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
                -e KAKAO_CLIENT_ID='${{ secrets.KAKAO_CLIENT_ID }}' \
                -e DEV_KAKAO_REDIRECT_URI='${{ secrets.DEV_KAKAO_REDIRECT_URI }}' \
                -e DEV_AI_BASE_URL='${{ secrets.DEV_AI_BASE_URL }}' \
                -e DEV_REDIS_HOST='${{ secrets.DEV_REDIS_HOST }}' \
                -e DEV_REDIS_PORT='${{ secrets.DEV_REDIS_PORT }}' \
                asia-northeast3-docker.pkg.dev/master-isotope-462503-m9/backend/cafeboo-back:latest"
